### ISSUE TITLE
bold keywords

### ISSUE THREAD

**Issue by Luk0r** [slgobinath/libreoffice-code-highlighter#1]
Hey tried and works (bot only for 5.0,  4.x is not working).
But bold keywords is not supported although it is set in the style.

anyway, thanks for the work, and especially for the clean tutorial with screenshots :)

**Comment by rugk** [comment]
What did you do? It worked for me when just manually making text bold, after the syntax highlighting.

**Comment by Luk0r** [comment]
Sorry, I cannot remember how I solved this or how I worked around it, too long ago ;)

**Comment by rugk** [comment]
Okay, but if you've solved it, you can at least close the issue.
