### ISSUE TITLE
Install in Ubuntu 16.04 fails and makes Writer unable to load

### ISSUE THREAD

**Issue by rastating** [slgobinath/libreoffice-code-highlighter#13]
When trying to install on Ubuntu 16.04 (x64) / Libre Office 5.1.6.2 (Build ID: 1:5.1.6-rc2-0ubuntu1-xenial2), the install crashes with the error:

```
C++ code threw St9bad_alloc: std::bad_alloc
```

At which point, Writer can't be started again, and the cache has to be manually cleared out from `~/.config/libreoffice/4/user/uno_packages/cache/`

**Comment by naraesk** [comment]
Had problems with Ubuntu 16.04 as well. After installing the extension, the menu bar was flickering (it appeared, it disappeared, it appeared ...) which made LibreOffice almost impossible to use. After disabling the extension everything went back to normal.

**Comment by slgobinath** [comment]
For menu flickering issue, please upgrade your LO. See https://github.com/slgobinath/libreoffice-code-highlighter/issues/11
