### ISSUE TITLE
Autoupdate on text change

### ISSUE THREAD

**Issue by rugk** [slgobinath/libreoffice-code-highlighter#15]
Currently when I change the text and want correct syntax highlighting again, I need to "re-highlight" the code again.

It would be nice if you could include an "auto-update" mode (maybe just as a setting).

**Comment by slgobinath** [comment]
Auto update is complex to implement as we need to continuously monitor the text and remember the code snippets. Closing this issue as won't fix.

**Comment by rugk** [comment]
So tag it as "wontfix" 😉
