### ISSUE TITLE
Autodetection mode

### ISSUE THREAD

**Issue by rugk** [slgobinath/libreoffice-code-highlighter#16]
Could we get an autodetection mode, so we do not have to search and select the correct language used?

https://highlightjs.org/ e.g. supports this.

**Comment by slgobinath** [comment]
Autodetection is added with https://github.com/slgobinath/libreoffice-code-highlighter/commit/57ac8b511f36146f8b04b73594973257ecbb14d8.
However, it is not perfect because it is hard to guess a language by syntax.

**Comment by slgobinath** [comment]
Included in new release 1.2
Please upgrade your extension
