### ISSUE TITLE
List of languages way too long

### ISSUE THREAD

**Issue by rugk** [slgobinath/libreoffice-code-highlighter#17]
It is nice you have support for so many languages, but it is really bad to need to search/scroll through this huge list of languages. One nearly needs 5 minutes or so just to find HTML.

To solve this, you may:
* list most common entries at the top, a seperation line and then everything else
* let users disable/enable entries, so they can choose by themselve, which languages they need

**Comment by Lesik** [comment]
I'd also be fine with typing "J" and then the first language starting with J is selected. Then I only have to go down a few entries to get to Java. Currently pressing a letter does nothing.

**Comment by rugk** [comment]
Yeah, that's also a good idea, but still not the best thing. So as an additional thing, yes.

**Comment by slgobinath** [comment]
Hi,
Since I am busy with my research and issues in other projects I maintain, I couldn't resolve recent issues in this extension. Once I get some time, I will improve the extension.

Thanks

**Comment by pintman** [comment]
Maybe another option would be to fold by the first Letter of the language.

**Comment by Lesik** [comment]
This solution, although not too elegantly looking, would be the simplest.

**Comment by slgobinath** [comment]
@pintman's solution is implemented and included in the new release 1.2.
Please upgrade your extension

I am thinking about an advanced solution with a toolbar. Depending on time availability, I will implement it.

**Comment by slgobinath** [comment]
Fixed by https://github.com/slgobinath/libreoffice-code-highlighter/pull/38
