### ISSUE TITLE
Can't use in fedora

### ISSUE THREAD

**Issue by tony-snail** [slgobinath/libreoffice-code-highlighter#21]
![2017-12-04 00-34-18](https://user-images.githubusercontent.com/30197105/33527395-fb0b22ee-d88a-11e7-9cd2-df3cb99b16b0.png)
I don't know is there have better way to fix it issues?

**Comment by TheElectronWill** [comment]
You have to install pygments for python before installing the extension:
```bash
sudo pip3 install pygments
```

**Comment by tony-snail** [comment]
@TheElectronWill 
thank for you help.

**Comment by slgobinath** [comment]
Closing this issue since it has been resolved.
Thank you @tony-snail

**Comment by ruben1981** [comment]
Not resolved at all. Even though you install pygments right before installing the extension, it still won't get it. 
![screenshot_20180518_153731](https://user-images.githubusercontent.com/10762465/40237785-af3fe742-5ab1-11e8-83f6-8c4b281f128b.png)
![screenshot_20180518_154055](https://user-images.githubusercontent.com/10762465/40237872-ee91de6e-5ab1-11e8-9d08-466277c5d861.png)
