### ISSUE TITLE
Customizing colors?

### ISSUE THREAD

**Issue by ahillio** [slgobinath/libreoffice-code-highlighter#22]
How are colors determined? Is control of the colors outside the scope of this extension, does it simply rely on pygments for that?

http://pygments.org/docs/styles/#creating-own-styles looks like something I could eventually figure out... would color styles created that way work with this extension?  Or would the extension need to be modified to allow for that?

**Comment by slgobinath** [comment]
Currently, this extension uses `default` color scheme. (See [highlight.py#L78](https://github.com/slgobinath/libreoffice-code-highlighter/blob/master/codehighlighter/python/highlight.py#L78)).

To let users change the color scheme, we need a preference dialog because I do not want to overwhelm the menu with more submenus for colors.

**Comment by jolange** [comment]
@slgobinath I'd like to implement that. Do you have some hint on how to add such a preference dialog?

I already made a custom version, where I hard-code the style, which works well. But I never developed an extension before, so I don't really know how that works. The resources I find on the internet are rather scarce, unfortunately.

**Comment by slgobinath** [comment]
Hi @jolange I appreciate your support.
Unfortunately I am also facing the same problem and I am not a LibreOffice extension expert (I developed this extension for personal use and made it open source). That is the main reason why I am not adding more features to this extension. I hope anyone who knows how to develop LibreOffice extension GUI would help us.

Thanks

**Comment by jolange** [comment]
Ok, thanks for the feedback! If I'll have some more time at some point, I will re-check what I can do. In the meantime, if someone has any useful advice, that would be much appreciated!

**Comment by axterbach** [comment]
@jolange I would suggest you to break the task into smaller pieces.

**Step 1:** Extend standard macro with UI elements
As references, you can check examples shipped with LibreOffice. Make a copy and play around with it. Check this demo for ex:
`Tools -> Macros -> Run Macro...`
`LibreOffice Macros -> Gimmicks -> Userfields -> StartChangesUserfields -> Run`

**Step 2:** Pass-to / Read-from UI elements
Learn how to "use" values from UI elements. Make it simple for now: create a dialog with just TextField and CommandButton. Try to cach a value from TextField on CommandButton click for ex.

Additional resources...

https://www.youtube.com/watch?v=qnl495qEEVU
Sure, it's example for the Calc but the concept is the same.

https://www.youtube.com/watch?v=xcN6XzuoaRA
Basic how-to example on Python bridge dialog

**Step 3:** Wrap it up
Now you just have to wrap-up all those segments, unless you gave up by now. :-)
As final concept you can go with something like: dialog with ComboBox / ListBox and CommandButton. To populate list element with available color schemes use local array. You can always throw complexity in the mix later (read list from external file).

**Comment by axterbach** [comment]
@slgobinath I have made some demo test functions. Please check attached archive for details.

[HLCode_Dlg_Demo.zip](https://github.com/slgobinath/libreoffice-code-highlighter/files/3511508/HLCode_Dlg_Demo.zip)

All macro related code grouped in `HLCode_Dlg_Demo.odt -> CodeHlLib -> CodeHlHelpers`

![PrtScr1](https://user-images.githubusercontent.com/5020738/63204931-8416dc80-c09d-11e9-9b76-d7c04f6b9212.png)
-
![PrtScr2](https://user-images.githubusercontent.com/5020738/63204936-8ed17180-c09d-11e9-91d2-99f59215de40.png)
-
In working version first two fields should be of type ListBox, I guess. And all menu items from `Tools -> Highlight Code` replaced with just one pointing to EXM4_ColorizeDlgShow() for ex.

I don't have much free time to spare at the moment so I couldn't complete the code 100% and close this task - sorry. I hope you can find this useful.

Best regards.

**Comment by slgobinath** [comment]
Thank you very much @axterbach 
I will continue from this. @jolange would you like to complete this?

**Comment by jolange** [comment]
Yes, I already started to play around on my own (the second video was helpful, thanks @axterbach).
I did not have a look at your code yet, but I'm sure I'll figure this out ;-)
