### ISSUE TITLE
Support for C++

### ISSUE THREAD

**Issue by naraesk** [slgobinath/libreoffice-code-highlighter#23]
I'm very happy I just found this extension, it's very helpful. Although I'm a bit surprised it supports so many languages, but not C++. How does it come? Is it possible to add support for C++?

**Comment by naraesk** [comment]
http://pygments.org/docs/lexers/#lexers-for-c-c-languages

Pygments supports C++

**Comment by slgobinath** [comment]
Really!!!!
I did not notice that. It is a shame not supporting C++. I will include it soon.

Thanks for pointing it out.

**Comment by slgobinath** [comment]
Added with https://github.com/slgobinath/libreoffice-code-highlighter/commit/e79d69b30c445cb413d37a5252ed791ecd7c00f7. I will release a new version soon.

**Comment by naraesk** [comment]
Awesome! Thanks!
Will try to install the current version, since I'd like to use it right now. Or when is "soon"?

**Comment by slgobinath** [comment]
Hi,
I have released the new version 1.3. Please upgrade the extension.
