### ISSUE TITLE
error executing the macro

### ISSUE THREAD

**Issue by mourKa86** [slgobinath/libreoffice-code-highlighter#3]
I would like to thank you for that work.

I actually followed the steps and uptill the end I got that error when I wanted to execute the macro

A Scripting Framework error occurred while running the Python script vnd.sun.star.script:Highlight.py$highlight_source_code?language=Python&location=share.

Message: <class 'ImportError'>: No module named 'pygments' (or 'pygments.styles' is unknown)
  /usr/lib/python3/dist-packages/uno.py:268 in function _uno_import() [return _g_delegatee( name, *optargs, **kwargs )]
  /usr/lib/python3/dist-packages/uno.py:342 in function _uno_import() [raise uno_import_exc]
  /usr/lib/libreoffice/share/Scripts/python/Highlight.py:1 in function <module>() [from pygments import styles]
  /usr/lib/libreoffice/program/pythonscript.py:452 in function getModuleByUrl() [exec(code, entry.module.__dict__)]
  /usr/lib/libreoffice/program/pythonscript.py:993 in function getScript() [mod = self.provCtx.getModuleByUrl( fileUri )]

**Comment by slgobinath** [comment]
Sorry for the delay @Abughazala. Could you please install the `pygments` module using either of these commands. (The command in README is incorrect).
`sudo pip3 install pygments`
`sudo apt install python3-pygments`
After installing this module, try the macro again. If it is not working, please do let me know.

**Comment by mourKa86** [comment]
sorry for the late reply as well @slgobinath 

it is working fine thank you very much :+1:
