### ISSUE TITLE
[feature request] IPython console highlighting

### ISSUE THREAD

**Issue by CarloLucibello** [slgobinath/libreoffice-code-highlighter#30]
currently only standard python console support is provided, while an input like this is not  highlighted correctly
```python
In [1]: x=1

In [2]: x+3
Out[2]: 4
```

**Comment by slgobinath** [comment]
Hi,
This extension depends on [Pygments](http://pygments.org/languages/) to highlight code snippets. Pygments does not provide this lexer. Therefore, I cannot provide this feature at the moment. If Pygments include it in future, I will update the extension as well.
Thanks
