### ISSUE TITLE
Support for R

### ISSUE THREAD

**Issue by arteteco** [slgobinath/libreoffice-code-highlighter#37]
Hello there,

is there any plan on including support for the R programming language?

**Comment by jolange** [comment]
It is supported by [pygments](http://pygments.org/languages/), which is used by this extension: "S, S-Plus, R".  See also [Wikipedia on R](https://en.wikipedia.org/wiki/R_(programming_language)#History).

You can choose `S`, or in the dialog included in the 1.7 release `r`.

**Comment by arteteco** [comment]
@jolange thanks for your reply. I have version 1.5, and I did not have the "R" entry in the menu. Wouldn't have guessed that I should have chosen "S", thanks for the tip!

Since it's included in the menu  in version 1.7 I'm closing the issue
