### ISSUE TITLE
Apply previous settings option not avalible

### ISSUE THREAD

**Issue by therayvoice** [slgobinath/libreoffice-code-highlighter#41]
It's not available in tools, and not available in customize.
A long list of stuff like highlight_html_default, highlight_js_default, etc. is available but nothing else.
 Apply previous settings option not available at all.

The extension is really great, yet shortcuts for custom code themes, and the ability to create custom themes will make it perfect.

**Comment by jolange** [comment]
The version in the [extensions archive](https://extensions.libreoffice.org/extensions/code-highlighter) is not completely up to date. You can "build" it on your own from this repo though, e.g. with this [bash script](https://github.com/slgobinath/libreoffice-code-highlighter/blob/master/build.sh) if you are on Linux/Unix.

**Comment by therayvoice** [comment]
Thanks.
