### ISSUE TITLE
Groovy, Kotlin: The last character of a highlighted word is not colored

### ISSUE THREAD

**Issue by braunharald** [slgobinath/libreoffice-code-highlighter#45]
Groovy, Kotlin: The last character of a highlighted word is not colored
[Groovy_colored.pdf](https://github.com/slgobinath/libreoffice-code-highlighter/files/6725046/Groovy_colored.pdf)
LibreOffice 7.1.4.2
Ubuntu 20.04.2
Python3 3.8.2

/Harald

**Comment by slgobinath** [comment]
Hi, I remember someone else also mentioned this issue. Can you try adding a space at the end of your code and run the extension again?

**Comment by braunharald** [comment]
I have now tested the following:
a) In my existing document, a space was inserted at the end of the text field with the code.
b) Create a new Writer document; created a text field with a code to be highlighted and executed "Highlight (default style) for Groovy" with no spaces at the end.

To a)
The extra space at the end has no effect. The last character of a highlighted word remains in its original state.

To b)
The error (the last character in each case is not converted) does not occur here at all.

I am now somewhat at a loss as to why this could be.

I enclose as an attachment
a) the newly created Writer text document
b) the existing document; Text field on page 54.

/ Harald
[New_Writer_Document.odt](https://github.com/slgobinath/libreoffice-code-highlighter/files/6731785/New_Writer_Document.odt)
[Existing_Document_Textfield_on_page_54.odt](https://github.com/slgobinath/libreoffice-code-highlighter/files/6731786/Existing_Document_Textfield_on_page_54.odt)
