### ISSUE TITLE
How to fix a "Scripting Framework error"

### ISSUE THREAD

**Issue by sunbearc22** [slgobinath/libreoffice-code-highlighter#53]
![image](https://user-images.githubusercontent.com/23432142/177564553-90f768f2-fb82-49f4-a140-a8baf5690ed7.png)

Any suggestion on how to fix this error? Can't highlight Python script. 

Had installed ea4db15f_codehighlighter.oxt, which is the latest release 1.6 from https://extensions.libreoffice.org/en/extensions/show/code-highlighter. 

Using LibreOffice Version: 6.4.7.2 Build ID: 1:6.4.7-0ubuntu0.20.04.4.

**Comment by sdasda7777** [comment]
I had the same issue, you have to remove the extension from LibreOffice, rename the extension file to "codehighlighter.oxt" and add it again.

**Comment by JMadgwick** [comment]
I have this error and renaming the file did not work for me.

**Comment by sdasda7777** [comment]
@JMadgwick This project is no longer maintained, use https://github.com/jmzambon/libreoffice-code-highlighter, it is a fork of this project and it has better UI and many more options.
