### ISSUE TITLE
Cannot be used in Centos 7 , need help!!

### ISSUE THREAD

**Issue by chihuyu** [slgobinath/libreoffice-code-highlighter#6]
hello, first i wanna thank you for this wonderful extension.
my system is centos 7 with python 2.7 pre-installed. 
i have installed python 3 as required. but i don't know how to install libreoffice-script-provider-python
python3  and  pygments under centos.
when i installed the extension and tried to highlight my code box , i saw an error page with the following info.
 
`A Scripting Framework error occurred while running the Python script vnd.sun.star.script:codehighlighter.oxt|python|highlight.py$highlight_arduino_default?language=Python&location=user:uno_packages.

Message: <type 'exceptions.ImportError'>: No module named pygments (or 'pygments.styles' is unknown)
  /usr/lib64/python2.7/site-packages/uno.py:338 in function _uno_import() [raise uno_import_exc]
  /home/fuck/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu13930stfvwb.tmp_/codehighlighter.oxt/python/highlight.py:19 in function <module>() [from pygments import styles]
  /usr/lib64/libreoffice/program/pythonscript.py:451 in function getModuleByUrl() [exec(code, entry.module.__dict__)]
  /usr/lib64/libreoffice/program/pythonscript.py:992 in function getScript() [mod = self.provCtx.getModuleByUrl( fileUri )]`

could you please instruct me to solve this annoying issue?  many thanks.

**Comment by slgobinath** [comment]
`A Scripting Framework error occurred while running the Python script` and `No module named pygments` mean you need to install `libreoffice-script-provider-python` and `pygments`.
I also don't have experience with Centos. However, I will try my best to find how to install them in Centos.

**Comment by chihuyu** [comment]
I have just install pygments and it seems all right for text box to function.
Do I still need to have libreoffice-script-provider-python ?  I wonder what it is. Is it a python module ? Where will I be able to download it?
Please reply. Thanks a lot.

**Comment by slgobinath** [comment]
Thanks for letting me know.
`libreoffice-script-provider-python` is the module used by LibreOffice to call the Python macros. I just now found in an [article](https://www.tecmint.com/install-libreoffice-on-rhel-centos-fedora-debian-ubuntu-linux-mint/) that this library is included in LibreOffice by default but in a different name `libobasis5.2-python-script-provider`. So nothing to worry about that library and keep using the addon.

Thanks & Regards,
Gobinath
