### ISSUE TITLE
Installation - Failed to register package for vnd.sun.star.expand

### ISSUE THREAD

**Issue by eternalbit** [slgobinath/libreoffice-code-highlighter#7]
When trying to install the extension ... after agreeing to the license agreement ... or afterwards when trying to enable it ... I get this error message and the extension cannot be enabled.

> Failed to register package for vnd.sun.star.expand:
$UNO_USER_PACKAGES_CACHE/uno_packages/lu138138sqi76.tmp_/codehighlighter.oxt/python

I installed all dependencies as written in the instructions.

When running ...
> sudo pip3 install pygments

... I get some message that my _.cache_ folder is owned by a different user but the installation completes with some kind of success message.

Any ideas?

**Comment by slgobinath** [comment]
Hi @eternalbit,
May I know your Linux distribution? Also please try to install `libreoffice-script-provider-python`. If it doesn't work, please share the complete error message.

Thanks

**Comment by eternalbit** [comment]
A Linux Mint release based on Ubuntu 16.04 64 bit.
As I wrote I installed the dependencies ... `libreoffice-script-provider-python` is installed.

I got rid of the above mentioned error message by running    _sudo **-H** pip3 install pygments_

So this error message is all I get:
> Failed to register package for vnd.sun.star.expand:
$UNO_USER_PACKAGES_CACHE/uno_packages/lu138138sqi76.tmp_/codehighlighter.oxt/python

**Comment by slgobinath** [comment]
Sorry I didn't notice that. I will try to reproduce this on my Linux Mint machine and let you know once I've found the reason.

**Comment by slgobinath** [comment]
I couldn't reproduce this problem in my Linux Mint 18.1 64 bit (based on Ubuntu 16.04). However based on the error message during `pip3` command you mentioned in the first comment, and the solution you've used in `sudo -H ...` I guess some permissions issues may be there.
Please check the owner and file permissions of this directory:
```
~/.config/libreoffice
```
If the current user has no write permission to this directory/subdirectories of it, that can be a reason.

**Comment by nicorikken** [comment]
I got the same error, because I kept LibreOffice running whilst installing the dependencies and trying to install the plugin. Restarting LibreOffice did the job.

**Comment by joshp23** [comment]
I had the same issue, @nicorikken's solution worked for me. Perhaps consider placing that insight into the docs? (to shut down LibreOffice while installing dependencies)

**Comment by slgobinath** [comment]
@nicorikken , @joshp23  thanks for pointing this out. I have updated the document.

**Comment by ajxn** [comment]
One might notice that there are two ways to install with `pip3`.  Either only for the local user running the command, or globally for all users on the system (and thus must be run as admin user root). When installing, the default is to install locally, at least in Debian. This according to `pip3 install --help`, which say the switch `--user` is default.

The command `pip3 install --user pygments` installs only for the user running the command.
The command `sudo -H pip3 install --system pygments` install pygments for all users.   The  switch `-H` to `sudo` set the home directory to root, to avoid warnings.

For checking the installation, try `pip3 show pygments`.  Notice the line "**Location:**".
(The package has "**Name: Pygments**" which isn't consistent with other packages on my system.  As others doesn't have capital character in the beginning of the name.

To check what packages is locally installed for this user, use `pip3 list --user`. The command `pip3 list` list all available packages, local as well as global.

So I would suggest this lines for global installations:
`sudo -H pip3 install --system pygments ; pip3 show pygments`
For local installations, I would use this:
`pip3 install --user pygments ; pip3 show pygments`

By the way, thanks for a very useful package.

**Comment by horaciosamaniego** [comment]
I have the same issue... I cannot install the libreoffice plugin on Ubuntu 18.04.1 LTS and libreoffice 

I still get the same error: 
`Couldn't Install LibreOffice Plugin The LibreOffice unopkg utility gave the following output: ERROR: Error binding package: vnd.sun.star.expand:$UNO_USER_PACKAGES_CACHE/uno_packages/lu163853yml7a.tmp_/Mendeley-1.18.oxt Cause: an error occurred during file opening unopkg failed. 
`
I wonder if this is related to the Mendeley version? My installation is v. 19 and the error states v.18

I also made sure to have the pigment library installed.

any help is deeply appreciated, please...


Horacio



Here is an output of all the libreoffice packages installed in my system:
```
:~$ dpkg -l | grep libreoffice | awk '{print $1, $2}' 
ii libreoffice-avmedia-backend-gstreamer
ii libreoffice-base-core
ii libreoffice-calc
ii libreoffice-common
ii libreoffice-core
ii libreoffice-draw
ii libreoffice-gnome
ii libreoffice-gtk3
ii libreoffice-help-en-gb
ii libreoffice-help-en-us
ii libreoffice-help-es
ii libreoffice-help-fr
ii libreoffice-help-it
ii libreoffice-impress
ii libreoffice-l10n-en-gb
ii libreoffice-l10n-en-za
ii libreoffice-l10n-es
ii libreoffice-l10n-fr
ii libreoffice-l10n-it
ii libreoffice-math
ii libreoffice-ogltrans
ii libreoffice-pdfimport
ii libreoffice-script-provider-python
ii libreoffice-style-breeze
ii libreoffice-style-galaxy
ii libreoffice-style-tango
ii libreoffice-texmaths
ii libreoffice-writer


```

**Comment by horaciosamaniego** [comment]
I managed to fix it... re-installed libreoffice, cleaned the .config/libreoffice/ folder that did it for me.

**Comment by Noblepal** [comment]
> Hi @eternalbit,
> May I know your Linux distribution? Also please try to install `libreoffice-script-provider-python`. If it doesn't work, please share the complete error message.
> 
> Thanks

Thank you, this worked for me

**Comment by Langlais115** [comment]
> Failed to register package for vnd.sun.star.expand:
> $UNO_USER_PACKAGES_CACHE/uno_packages/lu138138sqi76.tmp_/codehighlighter.oxt/python

The following did it for my:
`sudo apt-get install python3-pip`

`sudo -H pip3 install --system pygments`

`sudo apt install libreoffice-script-provider-python`
