### ISSUE TITLE
Support for Windows?

### ISSUE THREAD

**Issue by JoaoGFarias** [slgobinath/libreoffice-code-highlighter#8]
Does this extension support Windows' distribution of LibreOffice?

I having trouble when using the extension, although I have installed the pygments correctly.

![image](https://user-images.githubusercontent.com/1585655/28249478-fb4c56d2-6a2c-11e7-8fa1-9c753ce56acc.png)

![image](https://user-images.githubusercontent.com/1585655/28249479-01d92660-6a2d-11e7-8a52-86c4e74bf65e.png)

**Comment by slgobinath** [comment]
Hi,
I didn't test it in Windows. Can you make sure that the environment variable `PYTHONPATH` points to the correct location where the Python packages are installed?

**Comment by slgobinath** [comment]
Hi,
I have tested on Windows and setting `PYTHONPATH` resolves the problem.
Set the environment variable `PYTHONPATH` like this:
```
C:\Users\Joao\AppData\Local\Programs\Python\Python36-32\Lib\site-packages
```

**Comment by rugk** [comment]
Maybe mention his in the Readme?

**Comment by slgobinath** [comment]
@rugk fixed with https://github.com/slgobinath/libreoffice-code-highlighter/commit/5f9b34dc61255a59e673bb6d604087c54f22a2c8
